# Generated by Django 4.1 on 2022-09-15 17:11

from django.db import migrations, models
import face.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=50, verbose_name='Titre du cours')),
                ('matiere', models.CharField(max_length=100, verbose_name='Domaine du cours')),
                ('auteur', models.CharField(max_length=50, verbose_name='Auteur du cours')),
                ('doc', models.FileField(blank=True, null=True, upload_to='pdf', validators=[face.models.est_une_extension_autorise])),
                ('cover', models.ImageField(default='image/default.jpg', null=True, upload_to='image/', verbose_name='Veuiller mettre une image pour embellir le cours')),
                ('niveau', models.CharField(max_length=50, verbose_name='Niveau')),
                ('desc', models.TextField(null=True)),
                ('coef', models.IntegerField(null=True, verbose_name='Coeffcient de la matiere')),
            ],
        ),
    ]
