# Generated by Django 4.1 on 2022-09-12 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=50, verbose_name='Titre du cours')),
                ('auteur', models.CharField(max_length=50, verbose_name='Auteur du cours')),
                ('doc', models.ImageField(blank=True, null=True, upload_to='image/')),
                ('niveau', models.FloatField(max_length=50, verbose_name='Niveau')),
                ('desc', models.TextField(null=True)),
            ],
        ),
    ]
