# Generated by Django 4.1 on 2022-09-12 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cours',
            name='matiere',
            field=models.CharField(default='Non renseigne', max_length=100, verbose_name='Domaine du cours'),
        ),
    ]
