# Generated by Django 4.1 on 2022-09-12 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face', '0002_cours_matiere'),
    ]

    operations = [
        migrations.AddField(
            model_name='cours',
            name='coef',
            field=models.IntegerField(null=True, verbose_name='Coeffcient de la matiere'),
        ),
        migrations.AlterField(
            model_name='cours',
            name='doc',
            field=models.FileField(blank=True, null=True, upload_to='pdf/'),
        ),
        migrations.AlterField(
            model_name='cours',
            name='matiere',
            field=models.CharField(max_length=100, verbose_name='Domaine du cours'),
        ),
        migrations.AlterField(
            model_name='cours',
            name='niveau',
            field=models.CharField(max_length=50, verbose_name='Niveau'),
        ),
    ]
