# Generated by Django 4.1 on 2022-09-13 16:41

from django.db import migrations, models
import face.models


class Migration(migrations.Migration):

    dependencies = [
        ('face', '0004_alter_cours_doc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cours',
            name='doc',
            field=models.FileField(blank=True, null=True, upload_to='pdf', validators=[face.models.est_une_extension_autorise]),
        ),
    ]
