# Generated by Django 4.1 on 2022-09-13 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face', '0005_alter_cours_doc'),
    ]

    operations = [
        migrations.AddField(
            model_name='cours',
            name='cover',
            field=models.ImageField(default='image/default.jpg', null=True, upload_to='image/'),
        ),
    ]
